name: haskell-dapr
version: 0.1.0.0
github: githubuser/haskell-dapr
license: BSD3
author: Author name here
maintainer: example@example.com
copyright: 2022 Author name here

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on Github at <https://github.com/githubuser/haskell-dapr#readme>

dependencies:
  - base >= 4.11 && < 10
  - aeson
  - bytestring
  - hashmap
  - http-api-data
  - http-client
  - http-client-tls
  - http-types
  - req
  - rio
  - reflection
  - text

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - DeriveGeneric
  - DeriveAnyClass
  - DuplicateRecordFields

library:
  source-dirs: src
  other-modules:
  - Dapr.HttpClient.Internal

tests:
  haskell-dapr-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - haskell-dapr
      - hspec
      - hspec-core
      - QuickCheck

    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
