name: haskell-dapr
version: 0.1.0.0
github: nodew/haskell-dapr
license: Apache-2.0
author: Qiao Wang
maintainer: wangqiao11@hotmail.com
copyright: 2022 Qiao Wang

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on Github at <https://github.com/nodew/haskell-dapr#readme>

dependencies:
  - base >= 4.11 && < 10
  - aeson
  - bytestring
  - containers
  - exceptions
  - extra
  - req
  - reflection
  - text

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints

default-extensions:
  - OverloadedStrings
  - DataKinds
  - DeriveGeneric
  - DeriveAnyClass
  - DuplicateRecordFields

library:
  source-dirs: src
  other-modules:
  - Dapr.Client.HttpClient.Internal
  - Dapr.Common.Internal

tests:
  haskell-dapr-test-e2e:
    main: Spec.hs
    source-dirs: test/e2e
    dependencies:
      - haskell-dapr
      - hspec
      - hspec-core
      - QuickCheck

    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
