{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TypeApplications #-}
{-# OPTIONS_GHC -fno-warn-missing-export-lists #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}
{-# OPTIONS_GHC -fno-warn-unused-matches #-}

-- | Generated by Haskell protocol buffer compiler. DO NOT EDIT!
module Dapr.Proto.Common.V1.Common where
import qualified Prelude as Hs
import qualified Proto3.Suite.Class as HsProtobuf
import qualified Proto3.Suite.DotProto as HsProtobufAST
import qualified Proto3.Suite.JSONPB as HsJSONPB
import Proto3.Suite.JSONPB ((.=), (.:))
import qualified Proto3.Suite.Types as HsProtobuf
import qualified Proto3.Wire as HsProtobuf
import qualified Proto3.Wire.Decode as HsProtobuf
       (Parser, RawField)
import qualified Control.Applicative as Hs
import Control.Applicative ((<*>), (<|>), (<$>))
import qualified Control.DeepSeq as Hs
import qualified Control.Monad as Hs
import qualified Data.ByteString as Hs
import qualified Data.Coerce as Hs
import qualified Data.Int as Hs (Int16, Int32, Int64)
import qualified Data.List.NonEmpty as Hs (NonEmpty(..))
import qualified Data.Map as Hs (Map, mapKeysMonotonic)
import qualified Data.Proxy as Proxy
import qualified Data.String as Hs (fromString)
import qualified Data.Text.Lazy as Hs (Text)
import qualified Data.Vector as Hs (Vector)
import qualified Data.Word as Hs (Word16, Word32, Word64)
import qualified GHC.Enum as Hs
import qualified GHC.Generics as Hs
import qualified Google.Protobuf.Wrappers.Polymorphic as HsProtobuf
       (Wrapped(..))
import qualified Unsafe.Coerce as Hs
import qualified Google.Protobuf.Any
 
data HTTPExtension = HTTPExtension{httpextensionVerb ::
                                   HsProtobuf.Enumerated
                                     Dapr.Proto.Common.V1.Common.HTTPExtension_Verb,
                                   httpextensionQuerystring :: Hs.Text}
                   deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
 
instance Hs.NFData HTTPExtension
 
instance HsProtobuf.Named HTTPExtension where
        nameOf _ = (Hs.fromString "HTTPExtension")
 
instance HsProtobuf.HasDefault HTTPExtension
 
instance HsProtobuf.Message HTTPExtension where
        encodeMessage _
          HTTPExtension{httpextensionVerb = httpextensionVerb,
                        httpextensionQuerystring = httpextensionQuerystring}
          = (Hs.mconcat
               [(HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 1)
                   httpextensionVerb),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 2)
                   (Hs.coerce @(Hs.Text) @(HsProtobuf.String Hs.Text)
                      (httpextensionQuerystring)))])
        decodeMessage _
          = (Hs.pure HTTPExtension) <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 1))
              <*>
              (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @(Hs.Text)
                 (HsProtobuf.at HsProtobuf.decodeMessageField
                    (HsProtobuf.FieldNumber 2)))
        dotProto _
          = [(HsProtobufAST.DotProtoField (HsProtobuf.FieldNumber 1)
                (HsProtobufAST.Prim
                   (HsProtobufAST.Named (HsProtobufAST.Single "Verb")))
                (HsProtobufAST.Single "verb")
                []
                ""),
             (HsProtobufAST.DotProtoField (HsProtobuf.FieldNumber 2)
                (HsProtobufAST.Prim HsProtobufAST.String)
                (HsProtobufAST.Single "querystring")
                []
                "")]
 
instance HsJSONPB.ToJSONPB HTTPExtension where
        toJSONPB (HTTPExtension f1 f2)
          = (HsJSONPB.object
               ["verb" .= f1,
                "querystring" .=
                  (Hs.coerce @(Hs.Text) @(HsProtobuf.String Hs.Text) (f2))])
        toEncodingPB (HTTPExtension f1 f2)
          = (HsJSONPB.pairs
               ["verb" .= f1,
                "querystring" .=
                  (Hs.coerce @(Hs.Text) @(HsProtobuf.String Hs.Text) (f2))])
 
instance HsJSONPB.FromJSONPB HTTPExtension where
        parseJSONPB
          = (HsJSONPB.withObject "HTTPExtension"
               (\ obj ->
                  (Hs.pure HTTPExtension) <*> obj .: "verb" <*>
                    (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @(Hs.Text)
                       (obj .: "querystring"))))
 
instance HsJSONPB.ToJSON HTTPExtension where
        toJSON = HsJSONPB.toAesonValue
        toEncoding = HsJSONPB.toAesonEncoding
 
instance HsJSONPB.FromJSON HTTPExtension where
        parseJSON = HsJSONPB.parseJSONPB
 
instance HsJSONPB.ToSchema HTTPExtension where
        declareNamedSchema _
          = do let declare_verb = HsJSONPB.declareSchemaRef
               httpextensionVerb <- declare_verb Proxy.Proxy
               let declare_querystring = HsJSONPB.declareSchemaRef
               httpextensionQuerystring <- declare_querystring Proxy.Proxy
               let _ = Hs.pure HTTPExtension <*> HsJSONPB.asProxy declare_verb <*>
                         (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @(Hs.Text)
                            (HsJSONPB.asProxy declare_querystring))
               Hs.return
                 (HsJSONPB.NamedSchema{HsJSONPB._namedSchemaName =
                                         Hs.Just "HTTPExtension",
                                       HsJSONPB._namedSchemaSchema =
                                         Hs.mempty{HsJSONPB._schemaParamSchema =
                                                     Hs.mempty{HsJSONPB._paramSchemaType =
                                                                 Hs.Just HsJSONPB.SwaggerObject},
                                                   HsJSONPB._schemaProperties =
                                                     HsJSONPB.insOrdFromList
                                                       [("verb", httpextensionVerb),
                                                        ("querystring",
                                                         httpextensionQuerystring)]}})
 
data HTTPExtension_Verb = HTTPExtension_VerbNONE
                        | HTTPExtension_VerbGET
                        | HTTPExtension_VerbHEAD
                        | HTTPExtension_VerbPOST
                        | HTTPExtension_VerbPUT
                        | HTTPExtension_VerbDELETE
                        | HTTPExtension_VerbCONNECT
                        | HTTPExtension_VerbOPTIONS
                        | HTTPExtension_VerbTRACE
                        | HTTPExtension_VerbPATCH
                        deriving (Hs.Show, Hs.Eq, Hs.Generic, Hs.NFData)
 
instance HsProtobuf.Named HTTPExtension_Verb where
        nameOf _ = (Hs.fromString "HTTPExtension_Verb")
 
instance HsProtobuf.HasDefault HTTPExtension_Verb
 
instance Hs.Bounded HTTPExtension_Verb where
        minBound = HTTPExtension_VerbNONE
        maxBound = HTTPExtension_VerbPATCH
 
instance Hs.Ord HTTPExtension_Verb where
        compare x y
          = Hs.compare (HsProtobuf.fromProtoEnum x)
              (HsProtobuf.fromProtoEnum y)
 
instance HsProtobuf.ProtoEnum HTTPExtension_Verb where
        toProtoEnumMay 0 = Hs.Just HTTPExtension_VerbNONE
        toProtoEnumMay 1 = Hs.Just HTTPExtension_VerbGET
        toProtoEnumMay 2 = Hs.Just HTTPExtension_VerbHEAD
        toProtoEnumMay 3 = Hs.Just HTTPExtension_VerbPOST
        toProtoEnumMay 4 = Hs.Just HTTPExtension_VerbPUT
        toProtoEnumMay 5 = Hs.Just HTTPExtension_VerbDELETE
        toProtoEnumMay 6 = Hs.Just HTTPExtension_VerbCONNECT
        toProtoEnumMay 7 = Hs.Just HTTPExtension_VerbOPTIONS
        toProtoEnumMay 8 = Hs.Just HTTPExtension_VerbTRACE
        toProtoEnumMay 9 = Hs.Just HTTPExtension_VerbPATCH
        toProtoEnumMay _ = Hs.Nothing
        fromProtoEnum (HTTPExtension_VerbNONE) = 0
        fromProtoEnum (HTTPExtension_VerbGET) = 1
        fromProtoEnum (HTTPExtension_VerbHEAD) = 2
        fromProtoEnum (HTTPExtension_VerbPOST) = 3
        fromProtoEnum (HTTPExtension_VerbPUT) = 4
        fromProtoEnum (HTTPExtension_VerbDELETE) = 5
        fromProtoEnum (HTTPExtension_VerbCONNECT) = 6
        fromProtoEnum (HTTPExtension_VerbOPTIONS) = 7
        fromProtoEnum (HTTPExtension_VerbTRACE) = 8
        fromProtoEnum (HTTPExtension_VerbPATCH) = 9
 
instance HsJSONPB.ToJSONPB HTTPExtension_Verb where
        toJSONPB x _ = HsJSONPB.enumFieldString x
        toEncodingPB x _ = HsJSONPB.enumFieldEncoding x
 
instance HsJSONPB.FromJSONPB HTTPExtension_Verb where
        parseJSONPB (HsJSONPB.String "NONE")
          = Hs.pure HTTPExtension_VerbNONE
        parseJSONPB (HsJSONPB.String "GET") = Hs.pure HTTPExtension_VerbGET
        parseJSONPB (HsJSONPB.String "HEAD")
          = Hs.pure HTTPExtension_VerbHEAD
        parseJSONPB (HsJSONPB.String "POST")
          = Hs.pure HTTPExtension_VerbPOST
        parseJSONPB (HsJSONPB.String "PUT") = Hs.pure HTTPExtension_VerbPUT
        parseJSONPB (HsJSONPB.String "DELETE")
          = Hs.pure HTTPExtension_VerbDELETE
        parseJSONPB (HsJSONPB.String "CONNECT")
          = Hs.pure HTTPExtension_VerbCONNECT
        parseJSONPB (HsJSONPB.String "OPTIONS")
          = Hs.pure HTTPExtension_VerbOPTIONS
        parseJSONPB (HsJSONPB.String "TRACE")
          = Hs.pure HTTPExtension_VerbTRACE
        parseJSONPB (HsJSONPB.String "PATCH")
          = Hs.pure HTTPExtension_VerbPATCH
        parseJSONPB v = (HsJSONPB.typeMismatch "HTTPExtension_Verb" v)
 
instance HsJSONPB.ToJSON HTTPExtension_Verb where
        toJSON = HsJSONPB.toAesonValue
        toEncoding = HsJSONPB.toAesonEncoding
 
instance HsJSONPB.FromJSON HTTPExtension_Verb where
        parseJSON = HsJSONPB.parseJSONPB
 
instance HsProtobuf.Finite HTTPExtension_Verb
 
data InvokeRequest = InvokeRequest{invokeRequestMethod :: Hs.Text,
                                   invokeRequestData :: Hs.Maybe Google.Protobuf.Any.Any,
                                   invokeRequestContentType :: Hs.Text,
                                   invokeRequestHttpExtension ::
                                   Hs.Maybe Dapr.Proto.Common.V1.Common.HTTPExtension}
                   deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
 
instance Hs.NFData InvokeRequest
 
instance HsProtobuf.Named InvokeRequest where
        nameOf _ = (Hs.fromString "InvokeRequest")
 
instance HsProtobuf.HasDefault InvokeRequest
 
instance HsProtobuf.Message InvokeRequest where
        encodeMessage _
          InvokeRequest{invokeRequestMethod = invokeRequestMethod,
                        invokeRequestData = invokeRequestData,
                        invokeRequestContentType = invokeRequestContentType,
                        invokeRequestHttpExtension = invokeRequestHttpExtension}
          = (Hs.mconcat
               [(HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 1)
                   (Hs.coerce @(Hs.Text) @(HsProtobuf.String Hs.Text)
                      (invokeRequestMethod))),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 2)
                   (Hs.coerce @(Hs.Maybe Google.Protobuf.Any.Any)
                      @(HsProtobuf.Nested Google.Protobuf.Any.Any)
                      (invokeRequestData))),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 3)
                   (Hs.coerce @(Hs.Text) @(HsProtobuf.String Hs.Text)
                      (invokeRequestContentType))),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 4)
                   (Hs.coerce @(Hs.Maybe Dapr.Proto.Common.V1.Common.HTTPExtension)
                      @(HsProtobuf.Nested Dapr.Proto.Common.V1.Common.HTTPExtension)
                      (invokeRequestHttpExtension)))])
        decodeMessage _
          = (Hs.pure InvokeRequest) <*>
              (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @(Hs.Text)
                 (HsProtobuf.at HsProtobuf.decodeMessageField
                    (HsProtobuf.FieldNumber 1)))
              <*>
              (HsProtobuf.coerceOver @(HsProtobuf.Nested Google.Protobuf.Any.Any)
                 @(Hs.Maybe Google.Protobuf.Any.Any)
                 (HsProtobuf.at HsProtobuf.decodeMessageField
                    (HsProtobuf.FieldNumber 2)))
              <*>
              (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @(Hs.Text)
                 (HsProtobuf.at HsProtobuf.decodeMessageField
                    (HsProtobuf.FieldNumber 3)))
              <*>
              (HsProtobuf.coerceOver
                 @(HsProtobuf.Nested Dapr.Proto.Common.V1.Common.HTTPExtension)
                 @(Hs.Maybe Dapr.Proto.Common.V1.Common.HTTPExtension)
                 (HsProtobuf.at HsProtobuf.decodeMessageField
                    (HsProtobuf.FieldNumber 4)))
        dotProto _
          = [(HsProtobufAST.DotProtoField (HsProtobuf.FieldNumber 1)
                (HsProtobufAST.Prim HsProtobufAST.String)
                (HsProtobufAST.Single "method")
                []
                ""),
             (HsProtobufAST.DotProtoField (HsProtobuf.FieldNumber 2)
                (HsProtobufAST.Prim
                   (HsProtobufAST.Named
                      (HsProtobufAST.Dots
                         (HsProtobufAST.Path ("google" Hs.:| ["protobuf", "Any"])))))
                (HsProtobufAST.Single "data")
                []
                ""),
             (HsProtobufAST.DotProtoField (HsProtobuf.FieldNumber 3)
                (HsProtobufAST.Prim HsProtobufAST.String)
                (HsProtobufAST.Single "content_type")
                []
                ""),
             (HsProtobufAST.DotProtoField (HsProtobuf.FieldNumber 4)
                (HsProtobufAST.Prim
                   (HsProtobufAST.Named (HsProtobufAST.Single "HTTPExtension")))
                (HsProtobufAST.Single "http_extension")
                []
                "")]
 
instance HsJSONPB.ToJSONPB InvokeRequest where
        toJSONPB (InvokeRequest f1 f2 f3 f4)
          = (HsJSONPB.object
               ["method" .=
                  (Hs.coerce @(Hs.Text) @(HsProtobuf.String Hs.Text) (f1)),
                "data" .=
                  (Hs.coerce @(Hs.Maybe Google.Protobuf.Any.Any)
                     @(HsProtobuf.Nested Google.Protobuf.Any.Any)
                     (f2)),
                "content_type" .=
                  (Hs.coerce @(Hs.Text) @(HsProtobuf.String Hs.Text) (f3)),
                "http_extension" .=
                  (Hs.coerce @(Hs.Maybe Dapr.Proto.Common.V1.Common.HTTPExtension)
                     @(HsProtobuf.Nested Dapr.Proto.Common.V1.Common.HTTPExtension)
                     (f4))])
        toEncodingPB (InvokeRequest f1 f2 f3 f4)
          = (HsJSONPB.pairs
               ["method" .=
                  (Hs.coerce @(Hs.Text) @(HsProtobuf.String Hs.Text) (f1)),
                "data" .=
                  (Hs.coerce @(Hs.Maybe Google.Protobuf.Any.Any)
                     @(HsProtobuf.Nested Google.Protobuf.Any.Any)
                     (f2)),
                "content_type" .=
                  (Hs.coerce @(Hs.Text) @(HsProtobuf.String Hs.Text) (f3)),
                "http_extension" .=
                  (Hs.coerce @(Hs.Maybe Dapr.Proto.Common.V1.Common.HTTPExtension)
                     @(HsProtobuf.Nested Dapr.Proto.Common.V1.Common.HTTPExtension)
                     (f4))])
 
instance HsJSONPB.FromJSONPB InvokeRequest where
        parseJSONPB
          = (HsJSONPB.withObject "InvokeRequest"
               (\ obj ->
                  (Hs.pure InvokeRequest) <*>
                    (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @(Hs.Text)
                       (obj .: "method"))
                    <*>
                    (HsProtobuf.coerceOver @(HsProtobuf.Nested Google.Protobuf.Any.Any)
                       @(Hs.Maybe Google.Protobuf.Any.Any)
                       (obj .: "data"))
                    <*>
                    (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @(Hs.Text)
                       (obj .: "content_type"))
                    <*>
                    (HsProtobuf.coerceOver
                       @(HsProtobuf.Nested Dapr.Proto.Common.V1.Common.HTTPExtension)
                       @(Hs.Maybe Dapr.Proto.Common.V1.Common.HTTPExtension)
                       (obj .: "http_extension"))))
 
instance HsJSONPB.ToJSON InvokeRequest where
        toJSON = HsJSONPB.toAesonValue
        toEncoding = HsJSONPB.toAesonEncoding
 
instance HsJSONPB.FromJSON InvokeRequest where
        parseJSON = HsJSONPB.parseJSONPB
 
instance HsJSONPB.ToSchema InvokeRequest where
        declareNamedSchema _
          = do let declare_method = HsJSONPB.declareSchemaRef
               invokeRequestMethod <- declare_method Proxy.Proxy
               let declare_data = HsJSONPB.declareSchemaRef
               invokeRequestData <- declare_data Proxy.Proxy
               let declare_content_type = HsJSONPB.declareSchemaRef
               invokeRequestContentType <- declare_content_type Proxy.Proxy
               let declare_http_extension = HsJSONPB.declareSchemaRef
               invokeRequestHttpExtension <- declare_http_extension Proxy.Proxy
               let _ = Hs.pure InvokeRequest <*>
                         (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @(Hs.Text)
                            (HsJSONPB.asProxy declare_method))
                         <*>
                         (HsProtobuf.coerceOver @(HsProtobuf.Nested Google.Protobuf.Any.Any)
                            @(Hs.Maybe Google.Protobuf.Any.Any)
                            (HsJSONPB.asProxy declare_data))
                         <*>
                         (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @(Hs.Text)
                            (HsJSONPB.asProxy declare_content_type))
                         <*>
                         (HsProtobuf.coerceOver
                            @(HsProtobuf.Nested Dapr.Proto.Common.V1.Common.HTTPExtension)
                            @(Hs.Maybe Dapr.Proto.Common.V1.Common.HTTPExtension)
                            (HsJSONPB.asProxy declare_http_extension))
               Hs.return
                 (HsJSONPB.NamedSchema{HsJSONPB._namedSchemaName =
                                         Hs.Just "InvokeRequest",
                                       HsJSONPB._namedSchemaSchema =
                                         Hs.mempty{HsJSONPB._schemaParamSchema =
                                                     Hs.mempty{HsJSONPB._paramSchemaType =
                                                                 Hs.Just HsJSONPB.SwaggerObject},
                                                   HsJSONPB._schemaProperties =
                                                     HsJSONPB.insOrdFromList
                                                       [("method", invokeRequestMethod),
                                                        ("data", invokeRequestData),
                                                        ("content_type", invokeRequestContentType),
                                                        ("http_extension",
                                                         invokeRequestHttpExtension)]}})
 
data InvokeResponse = InvokeResponse{invokeResponseData ::
                                     Hs.Maybe Google.Protobuf.Any.Any,
                                     invokeResponseContentType :: Hs.Text}
                    deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
 
instance Hs.NFData InvokeResponse
 
instance HsProtobuf.Named InvokeResponse where
        nameOf _ = (Hs.fromString "InvokeResponse")
 
instance HsProtobuf.HasDefault InvokeResponse
 
instance HsProtobuf.Message InvokeResponse where
        encodeMessage _
          InvokeResponse{invokeResponseData = invokeResponseData,
                         invokeResponseContentType = invokeResponseContentType}
          = (Hs.mconcat
               [(HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 1)
                   (Hs.coerce @(Hs.Maybe Google.Protobuf.Any.Any)
                      @(HsProtobuf.Nested Google.Protobuf.Any.Any)
                      (invokeResponseData))),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 2)
                   (Hs.coerce @(Hs.Text) @(HsProtobuf.String Hs.Text)
                      (invokeResponseContentType)))])
        decodeMessage _
          = (Hs.pure InvokeResponse) <*>
              (HsProtobuf.coerceOver @(HsProtobuf.Nested Google.Protobuf.Any.Any)
                 @(Hs.Maybe Google.Protobuf.Any.Any)
                 (HsProtobuf.at HsProtobuf.decodeMessageField
                    (HsProtobuf.FieldNumber 1)))
              <*>
              (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @(Hs.Text)
                 (HsProtobuf.at HsProtobuf.decodeMessageField
                    (HsProtobuf.FieldNumber 2)))
        dotProto _
          = [(HsProtobufAST.DotProtoField (HsProtobuf.FieldNumber 1)
                (HsProtobufAST.Prim
                   (HsProtobufAST.Named
                      (HsProtobufAST.Dots
                         (HsProtobufAST.Path ("google" Hs.:| ["protobuf", "Any"])))))
                (HsProtobufAST.Single "data")
                []
                ""),
             (HsProtobufAST.DotProtoField (HsProtobuf.FieldNumber 2)
                (HsProtobufAST.Prim HsProtobufAST.String)
                (HsProtobufAST.Single "content_type")
                []
                "")]
 
instance HsJSONPB.ToJSONPB InvokeResponse where
        toJSONPB (InvokeResponse f1 f2)
          = (HsJSONPB.object
               ["data" .=
                  (Hs.coerce @(Hs.Maybe Google.Protobuf.Any.Any)
                     @(HsProtobuf.Nested Google.Protobuf.Any.Any)
                     (f1)),
                "content_type" .=
                  (Hs.coerce @(Hs.Text) @(HsProtobuf.String Hs.Text) (f2))])
        toEncodingPB (InvokeResponse f1 f2)
          = (HsJSONPB.pairs
               ["data" .=
                  (Hs.coerce @(Hs.Maybe Google.Protobuf.Any.Any)
                     @(HsProtobuf.Nested Google.Protobuf.Any.Any)
                     (f1)),
                "content_type" .=
                  (Hs.coerce @(Hs.Text) @(HsProtobuf.String Hs.Text) (f2))])
 
instance HsJSONPB.FromJSONPB InvokeResponse where
        parseJSONPB
          = (HsJSONPB.withObject "InvokeResponse"
               (\ obj ->
                  (Hs.pure InvokeResponse) <*>
                    (HsProtobuf.coerceOver @(HsProtobuf.Nested Google.Protobuf.Any.Any)
                       @(Hs.Maybe Google.Protobuf.Any.Any)
                       (obj .: "data"))
                    <*>
                    (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @(Hs.Text)
                       (obj .: "content_type"))))
 
instance HsJSONPB.ToJSON InvokeResponse where
        toJSON = HsJSONPB.toAesonValue
        toEncoding = HsJSONPB.toAesonEncoding
 
instance HsJSONPB.FromJSON InvokeResponse where
        parseJSON = HsJSONPB.parseJSONPB
 
instance HsJSONPB.ToSchema InvokeResponse where
        declareNamedSchema _
          = do let declare_data = HsJSONPB.declareSchemaRef
               invokeResponseData <- declare_data Proxy.Proxy
               let declare_content_type = HsJSONPB.declareSchemaRef
               invokeResponseContentType <- declare_content_type Proxy.Proxy
               let _ = Hs.pure InvokeResponse <*>
                         (HsProtobuf.coerceOver @(HsProtobuf.Nested Google.Protobuf.Any.Any)
                            @(Hs.Maybe Google.Protobuf.Any.Any)
                            (HsJSONPB.asProxy declare_data))
                         <*>
                         (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @(Hs.Text)
                            (HsJSONPB.asProxy declare_content_type))
               Hs.return
                 (HsJSONPB.NamedSchema{HsJSONPB._namedSchemaName =
                                         Hs.Just "InvokeResponse",
                                       HsJSONPB._namedSchemaSchema =
                                         Hs.mempty{HsJSONPB._schemaParamSchema =
                                                     Hs.mempty{HsJSONPB._paramSchemaType =
                                                                 Hs.Just HsJSONPB.SwaggerObject},
                                                   HsJSONPB._schemaProperties =
                                                     HsJSONPB.insOrdFromList
                                                       [("data", invokeResponseData),
                                                        ("content_type",
                                                         invokeResponseContentType)]}})
 
data StreamPayload = StreamPayload{streamPayloadData ::
                                   Hs.ByteString,
                                   streamPayloadSeq :: Hs.Word64}
                   deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
 
instance Hs.NFData StreamPayload
 
instance HsProtobuf.Named StreamPayload where
        nameOf _ = (Hs.fromString "StreamPayload")
 
instance HsProtobuf.HasDefault StreamPayload
 
instance HsProtobuf.Message StreamPayload where
        encodeMessage _
          StreamPayload{streamPayloadData = streamPayloadData,
                        streamPayloadSeq = streamPayloadSeq}
          = (Hs.mconcat
               [(HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 1)
                   (Hs.coerce @(Hs.ByteString) @(HsProtobuf.Bytes Hs.ByteString)
                      (streamPayloadData))),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 2)
                   streamPayloadSeq)])
        decodeMessage _
          = (Hs.pure StreamPayload) <*>
              (HsProtobuf.coerceOver @(HsProtobuf.Bytes Hs.ByteString)
                 @(Hs.ByteString)
                 (HsProtobuf.at HsProtobuf.decodeMessageField
                    (HsProtobuf.FieldNumber 1)))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 2))
        dotProto _
          = [(HsProtobufAST.DotProtoField (HsProtobuf.FieldNumber 1)
                (HsProtobufAST.Prim HsProtobufAST.Bytes)
                (HsProtobufAST.Single "data")
                []
                ""),
             (HsProtobufAST.DotProtoField (HsProtobuf.FieldNumber 2)
                (HsProtobufAST.Prim HsProtobufAST.UInt64)
                (HsProtobufAST.Single "seq")
                []
                "")]
 
instance HsJSONPB.ToJSONPB StreamPayload where
        toJSONPB (StreamPayload f1 f2)
          = (HsJSONPB.object
               ["data" .=
                  (Hs.coerce @(Hs.ByteString) @(HsProtobuf.Bytes Hs.ByteString)
                     (f1)),
                "seq" .= f2])
        toEncodingPB (StreamPayload f1 f2)
          = (HsJSONPB.pairs
               ["data" .=
                  (Hs.coerce @(Hs.ByteString) @(HsProtobuf.Bytes Hs.ByteString)
                     (f1)),
                "seq" .= f2])
 
instance HsJSONPB.FromJSONPB StreamPayload where
        parseJSONPB
          = (HsJSONPB.withObject "StreamPayload"
               (\ obj ->
                  (Hs.pure StreamPayload) <*>
                    (HsProtobuf.coerceOver @(HsProtobuf.Bytes Hs.ByteString)
                       @(Hs.ByteString)
                       (obj .: "data"))
                    <*> obj .: "seq"))
 
instance HsJSONPB.ToJSON StreamPayload where
        toJSON = HsJSONPB.toAesonValue
        toEncoding = HsJSONPB.toAesonEncoding
 
instance HsJSONPB.FromJSON StreamPayload where
        parseJSON = HsJSONPB.parseJSONPB
 
instance HsJSONPB.ToSchema StreamPayload where
        declareNamedSchema _
          = do let declare_data = HsJSONPB.declareSchemaRef
               streamPayloadData <- declare_data Proxy.Proxy
               let declare_seq = HsJSONPB.declareSchemaRef
               streamPayloadSeq <- declare_seq Proxy.Proxy
               let _ = Hs.pure StreamPayload <*>
                         (HsProtobuf.coerceOver @(HsProtobuf.Bytes Hs.ByteString)
                            @(Hs.ByteString)
                            (HsJSONPB.asProxy declare_data))
                         <*> HsJSONPB.asProxy declare_seq
               Hs.return
                 (HsJSONPB.NamedSchema{HsJSONPB._namedSchemaName =
                                         Hs.Just "StreamPayload",
                                       HsJSONPB._namedSchemaSchema =
                                         Hs.mempty{HsJSONPB._schemaParamSchema =
                                                     Hs.mempty{HsJSONPB._paramSchemaType =
                                                                 Hs.Just HsJSONPB.SwaggerObject},
                                                   HsJSONPB._schemaProperties =
                                                     HsJSONPB.insOrdFromList
                                                       [("data", streamPayloadData),
                                                        ("seq", streamPayloadSeq)]}})
 
data StateItem = StateItem{stateItemKey :: Hs.Text,
                           stateItemValue :: Hs.ByteString,
                           stateItemEtag :: Hs.Maybe Dapr.Proto.Common.V1.Common.Etag,
                           stateItemMetadata :: Hs.Map Hs.Text Hs.Text,
                           stateItemOptions ::
                           Hs.Maybe Dapr.Proto.Common.V1.Common.StateOptions}
               deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
 
instance Hs.NFData StateItem
 
instance HsProtobuf.Named StateItem where
        nameOf _ = (Hs.fromString "StateItem")
 
instance HsProtobuf.HasDefault StateItem
 
instance HsProtobuf.Message StateItem where
        encodeMessage _
          StateItem{stateItemKey = stateItemKey,
                    stateItemValue = stateItemValue, stateItemEtag = stateItemEtag,
                    stateItemMetadata = stateItemMetadata,
                    stateItemOptions = stateItemOptions}
          = (Hs.mconcat
               [(HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 1)
                   (Hs.coerce @(Hs.Text) @(HsProtobuf.String Hs.Text)
                      (stateItemKey))),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 2)
                   (Hs.coerce @(Hs.ByteString) @(HsProtobuf.Bytes Hs.ByteString)
                      (stateItemValue))),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 3)
                   (Hs.coerce @(Hs.Maybe Dapr.Proto.Common.V1.Common.Etag)
                      @(HsProtobuf.Nested Dapr.Proto.Common.V1.Common.Etag)
                      (stateItemEtag))),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 4)
                   (Hs.unsafeCoerce @(Hs.Map Hs.Text Hs.Text)
                      @(Hs.Map (HsProtobuf.String Hs.Text) (HsProtobuf.String Hs.Text))
                      (stateItemMetadata))),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 5)
                   (Hs.coerce @(Hs.Maybe Dapr.Proto.Common.V1.Common.StateOptions)
                      @(HsProtobuf.Nested Dapr.Proto.Common.V1.Common.StateOptions)
                      (stateItemOptions)))])
        decodeMessage _
          = (Hs.pure StateItem) <*>
              (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @(Hs.Text)
                 (HsProtobuf.at HsProtobuf.decodeMessageField
                    (HsProtobuf.FieldNumber 1)))
              <*>
              (HsProtobuf.coerceOver @(HsProtobuf.Bytes Hs.ByteString)
                 @(Hs.ByteString)
                 (HsProtobuf.at HsProtobuf.decodeMessageField
                    (HsProtobuf.FieldNumber 2)))
              <*>
              (HsProtobuf.coerceOver
                 @(HsProtobuf.Nested Dapr.Proto.Common.V1.Common.Etag)
                 @(Hs.Maybe Dapr.Proto.Common.V1.Common.Etag)
                 (HsProtobuf.at HsProtobuf.decodeMessageField
                    (HsProtobuf.FieldNumber 3)))
              <*>
              (HsProtobuf.unsafeCoerceOver
                 @(Hs.Map (HsProtobuf.String Hs.Text) (HsProtobuf.String Hs.Text))
                 @(Hs.Map Hs.Text Hs.Text)
                 (HsProtobuf.at HsProtobuf.decodeMessageField
                    (HsProtobuf.FieldNumber 4)))
              <*>
              (HsProtobuf.coerceOver
                 @(HsProtobuf.Nested Dapr.Proto.Common.V1.Common.StateOptions)
                 @(Hs.Maybe Dapr.Proto.Common.V1.Common.StateOptions)
                 (HsProtobuf.at HsProtobuf.decodeMessageField
                    (HsProtobuf.FieldNumber 5)))
        dotProto _
          = [(HsProtobufAST.DotProtoField (HsProtobuf.FieldNumber 1)
                (HsProtobufAST.Prim HsProtobufAST.String)
                (HsProtobufAST.Single "key")
                []
                ""),
             (HsProtobufAST.DotProtoField (HsProtobuf.FieldNumber 2)
                (HsProtobufAST.Prim HsProtobufAST.Bytes)
                (HsProtobufAST.Single "value")
                []
                ""),
             (HsProtobufAST.DotProtoField (HsProtobuf.FieldNumber 3)
                (HsProtobufAST.Prim
                   (HsProtobufAST.Named (HsProtobufAST.Single "Etag")))
                (HsProtobufAST.Single "etag")
                []
                ""),
             (HsProtobufAST.DotProtoField (HsProtobuf.FieldNumber 4)
                (HsProtobufAST.Map HsProtobufAST.String HsProtobufAST.String)
                (HsProtobufAST.Single "metadata")
                []
                ""),
             (HsProtobufAST.DotProtoField (HsProtobuf.FieldNumber 5)
                (HsProtobufAST.Prim
                   (HsProtobufAST.Named (HsProtobufAST.Single "StateOptions")))
                (HsProtobufAST.Single "options")
                []
                "")]
 
instance HsJSONPB.ToJSONPB StateItem where
        toJSONPB (StateItem f1 f2 f3 f4 f5)
          = (HsJSONPB.object
               ["key" .= (Hs.coerce @(Hs.Text) @(HsProtobuf.String Hs.Text) (f1)),
                "value" .=
                  (Hs.coerce @(Hs.ByteString) @(HsProtobuf.Bytes Hs.ByteString)
                     (f2)),
                "etag" .=
                  (Hs.coerce @(Hs.Maybe Dapr.Proto.Common.V1.Common.Etag)
                     @(HsProtobuf.Nested Dapr.Proto.Common.V1.Common.Etag)
                     (f3)),
                "metadata" .=
                  (Hs.unsafeCoerce @(Hs.Map Hs.Text Hs.Text)
                     @(Hs.Map (HsProtobuf.String Hs.Text) (HsProtobuf.String Hs.Text))
                     (f4)),
                "options" .=
                  (Hs.coerce @(Hs.Maybe Dapr.Proto.Common.V1.Common.StateOptions)
                     @(HsProtobuf.Nested Dapr.Proto.Common.V1.Common.StateOptions)
                     (f5))])
        toEncodingPB (StateItem f1 f2 f3 f4 f5)
          = (HsJSONPB.pairs
               ["key" .= (Hs.coerce @(Hs.Text) @(HsProtobuf.String Hs.Text) (f1)),
                "value" .=
                  (Hs.coerce @(Hs.ByteString) @(HsProtobuf.Bytes Hs.ByteString)
                     (f2)),
                "etag" .=
                  (Hs.coerce @(Hs.Maybe Dapr.Proto.Common.V1.Common.Etag)
                     @(HsProtobuf.Nested Dapr.Proto.Common.V1.Common.Etag)
                     (f3)),
                "metadata" .=
                  (Hs.unsafeCoerce @(Hs.Map Hs.Text Hs.Text)
                     @(Hs.Map (HsProtobuf.String Hs.Text) (HsProtobuf.String Hs.Text))
                     (f4)),
                "options" .=
                  (Hs.coerce @(Hs.Maybe Dapr.Proto.Common.V1.Common.StateOptions)
                     @(HsProtobuf.Nested Dapr.Proto.Common.V1.Common.StateOptions)
                     (f5))])
 
instance HsJSONPB.FromJSONPB StateItem where
        parseJSONPB
          = (HsJSONPB.withObject "StateItem"
               (\ obj ->
                  (Hs.pure StateItem) <*>
                    (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @(Hs.Text)
                       (obj .: "key"))
                    <*>
                    (HsProtobuf.coerceOver @(HsProtobuf.Bytes Hs.ByteString)
                       @(Hs.ByteString)
                       (obj .: "value"))
                    <*>
                    (HsProtobuf.coerceOver
                       @(HsProtobuf.Nested Dapr.Proto.Common.V1.Common.Etag)
                       @(Hs.Maybe Dapr.Proto.Common.V1.Common.Etag)
                       (obj .: "etag"))
                    <*>
                    (HsProtobuf.unsafeCoerceOver
                       @(Hs.Map (HsProtobuf.String Hs.Text) (HsProtobuf.String Hs.Text))
                       @(Hs.Map Hs.Text Hs.Text)
                       (obj .: "metadata"))
                    <*>
                    (HsProtobuf.coerceOver
                       @(HsProtobuf.Nested Dapr.Proto.Common.V1.Common.StateOptions)
                       @(Hs.Maybe Dapr.Proto.Common.V1.Common.StateOptions)
                       (obj .: "options"))))
 
instance HsJSONPB.ToJSON StateItem where
        toJSON = HsJSONPB.toAesonValue
        toEncoding = HsJSONPB.toAesonEncoding
 
instance HsJSONPB.FromJSON StateItem where
        parseJSON = HsJSONPB.parseJSONPB
 
instance HsJSONPB.ToSchema StateItem where
        declareNamedSchema _
          = do let declare_key = HsJSONPB.declareSchemaRef
               stateItemKey <- declare_key Proxy.Proxy
               let declare_value = HsJSONPB.declareSchemaRef
               stateItemValue <- declare_value Proxy.Proxy
               let declare_etag = HsJSONPB.declareSchemaRef
               stateItemEtag <- declare_etag Proxy.Proxy
               let declare_metadata = HsJSONPB.declareSchemaRef
               stateItemMetadata <- declare_metadata Proxy.Proxy
               let declare_options = HsJSONPB.declareSchemaRef
               stateItemOptions <- declare_options Proxy.Proxy
               let _ = Hs.pure StateItem <*>
                         (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @(Hs.Text)
                            (HsJSONPB.asProxy declare_key))
                         <*>
                         (HsProtobuf.coerceOver @(HsProtobuf.Bytes Hs.ByteString)
                            @(Hs.ByteString)
                            (HsJSONPB.asProxy declare_value))
                         <*>
                         (HsProtobuf.coerceOver
                            @(HsProtobuf.Nested Dapr.Proto.Common.V1.Common.Etag)
                            @(Hs.Maybe Dapr.Proto.Common.V1.Common.Etag)
                            (HsJSONPB.asProxy declare_etag))
                         <*>
                         (HsProtobuf.unsafeCoerceOver
                            @(Hs.Map (HsProtobuf.String Hs.Text) (HsProtobuf.String Hs.Text))
                            @(Hs.Map Hs.Text Hs.Text)
                            (HsJSONPB.asProxy declare_metadata))
                         <*>
                         (HsProtobuf.coerceOver
                            @(HsProtobuf.Nested Dapr.Proto.Common.V1.Common.StateOptions)
                            @(Hs.Maybe Dapr.Proto.Common.V1.Common.StateOptions)
                            (HsJSONPB.asProxy declare_options))
               Hs.return
                 (HsJSONPB.NamedSchema{HsJSONPB._namedSchemaName =
                                         Hs.Just "StateItem",
                                       HsJSONPB._namedSchemaSchema =
                                         Hs.mempty{HsJSONPB._schemaParamSchema =
                                                     Hs.mempty{HsJSONPB._paramSchemaType =
                                                                 Hs.Just HsJSONPB.SwaggerObject},
                                                   HsJSONPB._schemaProperties =
                                                     HsJSONPB.insOrdFromList
                                                       [("key", stateItemKey),
                                                        ("value", stateItemValue),
                                                        ("etag", stateItemEtag),
                                                        ("metadata", stateItemMetadata),
                                                        ("options", stateItemOptions)]}})
 
newtype Etag = Etag{etagValue :: Hs.Text}
               deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
 
instance Hs.NFData Etag
 
instance HsProtobuf.Named Etag where
        nameOf _ = (Hs.fromString "Etag")
 
instance HsProtobuf.HasDefault Etag
 
instance HsProtobuf.Message Etag where
        encodeMessage _ Etag{etagValue = etagValue}
          = (Hs.mconcat
               [(HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 1)
                   (Hs.coerce @(Hs.Text) @(HsProtobuf.String Hs.Text) (etagValue)))])
        decodeMessage _
          = (Hs.pure Etag) <*>
              (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @(Hs.Text)
                 (HsProtobuf.at HsProtobuf.decodeMessageField
                    (HsProtobuf.FieldNumber 1)))
        dotProto _
          = [(HsProtobufAST.DotProtoField (HsProtobuf.FieldNumber 1)
                (HsProtobufAST.Prim HsProtobufAST.String)
                (HsProtobufAST.Single "value")
                []
                "")]
 
instance HsJSONPB.ToJSONPB Etag where
        toJSONPB (Etag f1)
          = (HsJSONPB.object
               ["value" .=
                  (Hs.coerce @(Hs.Text) @(HsProtobuf.String Hs.Text) (f1))])
        toEncodingPB (Etag f1)
          = (HsJSONPB.pairs
               ["value" .=
                  (Hs.coerce @(Hs.Text) @(HsProtobuf.String Hs.Text) (f1))])
 
instance HsJSONPB.FromJSONPB Etag where
        parseJSONPB
          = (HsJSONPB.withObject "Etag"
               (\ obj ->
                  (Hs.pure Etag) <*>
                    (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @(Hs.Text)
                       (obj .: "value"))))
 
instance HsJSONPB.ToJSON Etag where
        toJSON = HsJSONPB.toAesonValue
        toEncoding = HsJSONPB.toAesonEncoding
 
instance HsJSONPB.FromJSON Etag where
        parseJSON = HsJSONPB.parseJSONPB
 
instance HsJSONPB.ToSchema Etag where
        declareNamedSchema _
          = do let declare_value = HsJSONPB.declareSchemaRef
               etagValue <- declare_value Proxy.Proxy
               let _ = Hs.pure Etag <*>
                         (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @(Hs.Text)
                            (HsJSONPB.asProxy declare_value))
               Hs.return
                 (HsJSONPB.NamedSchema{HsJSONPB._namedSchemaName = Hs.Just "Etag",
                                       HsJSONPB._namedSchemaSchema =
                                         Hs.mempty{HsJSONPB._schemaParamSchema =
                                                     Hs.mempty{HsJSONPB._paramSchemaType =
                                                                 Hs.Just HsJSONPB.SwaggerObject},
                                                   HsJSONPB._schemaProperties =
                                                     HsJSONPB.insOrdFromList
                                                       [("value", etagValue)]}})
 
data StateOptions = StateOptions{stateOptionsConcurrency ::
                                 HsProtobuf.Enumerated
                                   Dapr.Proto.Common.V1.Common.StateOptions_StateConcurrency,
                                 stateOptionsConsistency ::
                                 HsProtobuf.Enumerated
                                   Dapr.Proto.Common.V1.Common.StateOptions_StateConsistency}
                  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
 
instance Hs.NFData StateOptions
 
instance HsProtobuf.Named StateOptions where
        nameOf _ = (Hs.fromString "StateOptions")
 
instance HsProtobuf.HasDefault StateOptions
 
instance HsProtobuf.Message StateOptions where
        encodeMessage _
          StateOptions{stateOptionsConcurrency = stateOptionsConcurrency,
                       stateOptionsConsistency = stateOptionsConsistency}
          = (Hs.mconcat
               [(HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 1)
                   stateOptionsConcurrency),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 2)
                   stateOptionsConsistency)])
        decodeMessage _
          = (Hs.pure StateOptions) <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 1))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 2))
        dotProto _
          = [(HsProtobufAST.DotProtoField (HsProtobuf.FieldNumber 1)
                (HsProtobufAST.Prim
                   (HsProtobufAST.Named (HsProtobufAST.Single "StateConcurrency")))
                (HsProtobufAST.Single "concurrency")
                []
                ""),
             (HsProtobufAST.DotProtoField (HsProtobuf.FieldNumber 2)
                (HsProtobufAST.Prim
                   (HsProtobufAST.Named (HsProtobufAST.Single "StateConsistency")))
                (HsProtobufAST.Single "consistency")
                []
                "")]
 
instance HsJSONPB.ToJSONPB StateOptions where
        toJSONPB (StateOptions f1 f2)
          = (HsJSONPB.object ["concurrency" .= f1, "consistency" .= f2])
        toEncodingPB (StateOptions f1 f2)
          = (HsJSONPB.pairs ["concurrency" .= f1, "consistency" .= f2])
 
instance HsJSONPB.FromJSONPB StateOptions where
        parseJSONPB
          = (HsJSONPB.withObject "StateOptions"
               (\ obj ->
                  (Hs.pure StateOptions) <*> obj .: "concurrency" <*>
                    obj .: "consistency"))
 
instance HsJSONPB.ToJSON StateOptions where
        toJSON = HsJSONPB.toAesonValue
        toEncoding = HsJSONPB.toAesonEncoding
 
instance HsJSONPB.FromJSON StateOptions where
        parseJSON = HsJSONPB.parseJSONPB
 
instance HsJSONPB.ToSchema StateOptions where
        declareNamedSchema _
          = do let declare_concurrency = HsJSONPB.declareSchemaRef
               stateOptionsConcurrency <- declare_concurrency Proxy.Proxy
               let declare_consistency = HsJSONPB.declareSchemaRef
               stateOptionsConsistency <- declare_consistency Proxy.Proxy
               let _ = Hs.pure StateOptions <*>
                         HsJSONPB.asProxy declare_concurrency
                         <*> HsJSONPB.asProxy declare_consistency
               Hs.return
                 (HsJSONPB.NamedSchema{HsJSONPB._namedSchemaName =
                                         Hs.Just "StateOptions",
                                       HsJSONPB._namedSchemaSchema =
                                         Hs.mempty{HsJSONPB._schemaParamSchema =
                                                     Hs.mempty{HsJSONPB._paramSchemaType =
                                                                 Hs.Just HsJSONPB.SwaggerObject},
                                                   HsJSONPB._schemaProperties =
                                                     HsJSONPB.insOrdFromList
                                                       [("concurrency", stateOptionsConcurrency),
                                                        ("consistency", stateOptionsConsistency)]}})
 
data StateOptions_StateConcurrency = StateOptions_StateConcurrencyCONCURRENCY_UNSPECIFIED
                                   | StateOptions_StateConcurrencyCONCURRENCY_FIRST_WRITE
                                   | StateOptions_StateConcurrencyCONCURRENCY_LAST_WRITE
                                   deriving (Hs.Show, Hs.Eq, Hs.Generic, Hs.NFData)
 
instance HsProtobuf.Named StateOptions_StateConcurrency where
        nameOf _ = (Hs.fromString "StateOptions_StateConcurrency")
 
instance HsProtobuf.HasDefault StateOptions_StateConcurrency
 
instance Hs.Bounded StateOptions_StateConcurrency where
        minBound = StateOptions_StateConcurrencyCONCURRENCY_UNSPECIFIED
        maxBound = StateOptions_StateConcurrencyCONCURRENCY_LAST_WRITE
 
instance Hs.Ord StateOptions_StateConcurrency where
        compare x y
          = Hs.compare (HsProtobuf.fromProtoEnum x)
              (HsProtobuf.fromProtoEnum y)
 
instance HsProtobuf.ProtoEnum StateOptions_StateConcurrency where
        toProtoEnumMay 0
          = Hs.Just StateOptions_StateConcurrencyCONCURRENCY_UNSPECIFIED
        toProtoEnumMay 1
          = Hs.Just StateOptions_StateConcurrencyCONCURRENCY_FIRST_WRITE
        toProtoEnumMay 2
          = Hs.Just StateOptions_StateConcurrencyCONCURRENCY_LAST_WRITE
        toProtoEnumMay _ = Hs.Nothing
        fromProtoEnum
          (StateOptions_StateConcurrencyCONCURRENCY_UNSPECIFIED) = 0
        fromProtoEnum
          (StateOptions_StateConcurrencyCONCURRENCY_FIRST_WRITE) = 1
        fromProtoEnum (StateOptions_StateConcurrencyCONCURRENCY_LAST_WRITE)
          = 2
 
instance HsJSONPB.ToJSONPB StateOptions_StateConcurrency where
        toJSONPB x _ = HsJSONPB.enumFieldString x
        toEncodingPB x _ = HsJSONPB.enumFieldEncoding x
 
instance HsJSONPB.FromJSONPB StateOptions_StateConcurrency where
        parseJSONPB (HsJSONPB.String "CONCURRENCY_UNSPECIFIED")
          = Hs.pure StateOptions_StateConcurrencyCONCURRENCY_UNSPECIFIED
        parseJSONPB (HsJSONPB.String "CONCURRENCY_FIRST_WRITE")
          = Hs.pure StateOptions_StateConcurrencyCONCURRENCY_FIRST_WRITE
        parseJSONPB (HsJSONPB.String "CONCURRENCY_LAST_WRITE")
          = Hs.pure StateOptions_StateConcurrencyCONCURRENCY_LAST_WRITE
        parseJSONPB v
          = (HsJSONPB.typeMismatch "StateOptions_StateConcurrency" v)
 
instance HsJSONPB.ToJSON StateOptions_StateConcurrency where
        toJSON = HsJSONPB.toAesonValue
        toEncoding = HsJSONPB.toAesonEncoding
 
instance HsJSONPB.FromJSON StateOptions_StateConcurrency where
        parseJSON = HsJSONPB.parseJSONPB
 
instance HsProtobuf.Finite StateOptions_StateConcurrency
 
data StateOptions_StateConsistency = StateOptions_StateConsistencyCONSISTENCY_UNSPECIFIED
                                   | StateOptions_StateConsistencyCONSISTENCY_EVENTUAL
                                   | StateOptions_StateConsistencyCONSISTENCY_STRONG
                                   deriving (Hs.Show, Hs.Eq, Hs.Generic, Hs.NFData)
 
instance HsProtobuf.Named StateOptions_StateConsistency where
        nameOf _ = (Hs.fromString "StateOptions_StateConsistency")
 
instance HsProtobuf.HasDefault StateOptions_StateConsistency
 
instance Hs.Bounded StateOptions_StateConsistency where
        minBound = StateOptions_StateConsistencyCONSISTENCY_UNSPECIFIED
        maxBound = StateOptions_StateConsistencyCONSISTENCY_STRONG
 
instance Hs.Ord StateOptions_StateConsistency where
        compare x y
          = Hs.compare (HsProtobuf.fromProtoEnum x)
              (HsProtobuf.fromProtoEnum y)
 
instance HsProtobuf.ProtoEnum StateOptions_StateConsistency where
        toProtoEnumMay 0
          = Hs.Just StateOptions_StateConsistencyCONSISTENCY_UNSPECIFIED
        toProtoEnumMay 1
          = Hs.Just StateOptions_StateConsistencyCONSISTENCY_EVENTUAL
        toProtoEnumMay 2
          = Hs.Just StateOptions_StateConsistencyCONSISTENCY_STRONG
        toProtoEnumMay _ = Hs.Nothing
        fromProtoEnum
          (StateOptions_StateConsistencyCONSISTENCY_UNSPECIFIED) = 0
        fromProtoEnum (StateOptions_StateConsistencyCONSISTENCY_EVENTUAL)
          = 1
        fromProtoEnum (StateOptions_StateConsistencyCONSISTENCY_STRONG) = 2
 
instance HsJSONPB.ToJSONPB StateOptions_StateConsistency where
        toJSONPB x _ = HsJSONPB.enumFieldString x
        toEncodingPB x _ = HsJSONPB.enumFieldEncoding x
 
instance HsJSONPB.FromJSONPB StateOptions_StateConsistency where
        parseJSONPB (HsJSONPB.String "CONSISTENCY_UNSPECIFIED")
          = Hs.pure StateOptions_StateConsistencyCONSISTENCY_UNSPECIFIED
        parseJSONPB (HsJSONPB.String "CONSISTENCY_EVENTUAL")
          = Hs.pure StateOptions_StateConsistencyCONSISTENCY_EVENTUAL
        parseJSONPB (HsJSONPB.String "CONSISTENCY_STRONG")
          = Hs.pure StateOptions_StateConsistencyCONSISTENCY_STRONG
        parseJSONPB v
          = (HsJSONPB.typeMismatch "StateOptions_StateConsistency" v)
 
instance HsJSONPB.ToJSON StateOptions_StateConsistency where
        toJSON = HsJSONPB.toAesonValue
        toEncoding = HsJSONPB.toAesonEncoding
 
instance HsJSONPB.FromJSON StateOptions_StateConsistency where
        parseJSON = HsJSONPB.parseJSONPB
 
instance HsProtobuf.Finite StateOptions_StateConsistency
 
data ConfigurationItem = ConfigurationItem{configurationItemValue
                                           :: Hs.Text,
                                           configurationItemVersion :: Hs.Text,
                                           configurationItemMetadata :: Hs.Map Hs.Text Hs.Text}
                       deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
 
instance Hs.NFData ConfigurationItem
 
instance HsProtobuf.Named ConfigurationItem where
        nameOf _ = (Hs.fromString "ConfigurationItem")
 
instance HsProtobuf.HasDefault ConfigurationItem
 
instance HsProtobuf.Message ConfigurationItem where
        encodeMessage _
          ConfigurationItem{configurationItemValue = configurationItemValue,
                            configurationItemVersion = configurationItemVersion,
                            configurationItemMetadata = configurationItemMetadata}
          = (Hs.mconcat
               [(HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 1)
                   (Hs.coerce @(Hs.Text) @(HsProtobuf.String Hs.Text)
                      (configurationItemValue))),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 2)
                   (Hs.coerce @(Hs.Text) @(HsProtobuf.String Hs.Text)
                      (configurationItemVersion))),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 3)
                   (Hs.unsafeCoerce @(Hs.Map Hs.Text Hs.Text)
                      @(Hs.Map (HsProtobuf.String Hs.Text) (HsProtobuf.String Hs.Text))
                      (configurationItemMetadata)))])
        decodeMessage _
          = (Hs.pure ConfigurationItem) <*>
              (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @(Hs.Text)
                 (HsProtobuf.at HsProtobuf.decodeMessageField
                    (HsProtobuf.FieldNumber 1)))
              <*>
              (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @(Hs.Text)
                 (HsProtobuf.at HsProtobuf.decodeMessageField
                    (HsProtobuf.FieldNumber 2)))
              <*>
              (HsProtobuf.unsafeCoerceOver
                 @(Hs.Map (HsProtobuf.String Hs.Text) (HsProtobuf.String Hs.Text))
                 @(Hs.Map Hs.Text Hs.Text)
                 (HsProtobuf.at HsProtobuf.decodeMessageField
                    (HsProtobuf.FieldNumber 3)))
        dotProto _
          = [(HsProtobufAST.DotProtoField (HsProtobuf.FieldNumber 1)
                (HsProtobufAST.Prim HsProtobufAST.String)
                (HsProtobufAST.Single "value")
                []
                ""),
             (HsProtobufAST.DotProtoField (HsProtobuf.FieldNumber 2)
                (HsProtobufAST.Prim HsProtobufAST.String)
                (HsProtobufAST.Single "version")
                []
                ""),
             (HsProtobufAST.DotProtoField (HsProtobuf.FieldNumber 3)
                (HsProtobufAST.Map HsProtobufAST.String HsProtobufAST.String)
                (HsProtobufAST.Single "metadata")
                []
                "")]
 
instance HsJSONPB.ToJSONPB ConfigurationItem where
        toJSONPB (ConfigurationItem f1 f2 f3)
          = (HsJSONPB.object
               ["value" .=
                  (Hs.coerce @(Hs.Text) @(HsProtobuf.String Hs.Text) (f1)),
                "version" .=
                  (Hs.coerce @(Hs.Text) @(HsProtobuf.String Hs.Text) (f2)),
                "metadata" .=
                  (Hs.unsafeCoerce @(Hs.Map Hs.Text Hs.Text)
                     @(Hs.Map (HsProtobuf.String Hs.Text) (HsProtobuf.String Hs.Text))
                     (f3))])
        toEncodingPB (ConfigurationItem f1 f2 f3)
          = (HsJSONPB.pairs
               ["value" .=
                  (Hs.coerce @(Hs.Text) @(HsProtobuf.String Hs.Text) (f1)),
                "version" .=
                  (Hs.coerce @(Hs.Text) @(HsProtobuf.String Hs.Text) (f2)),
                "metadata" .=
                  (Hs.unsafeCoerce @(Hs.Map Hs.Text Hs.Text)
                     @(Hs.Map (HsProtobuf.String Hs.Text) (HsProtobuf.String Hs.Text))
                     (f3))])
 
instance HsJSONPB.FromJSONPB ConfigurationItem where
        parseJSONPB
          = (HsJSONPB.withObject "ConfigurationItem"
               (\ obj ->
                  (Hs.pure ConfigurationItem) <*>
                    (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @(Hs.Text)
                       (obj .: "value"))
                    <*>
                    (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @(Hs.Text)
                       (obj .: "version"))
                    <*>
                    (HsProtobuf.unsafeCoerceOver
                       @(Hs.Map (HsProtobuf.String Hs.Text) (HsProtobuf.String Hs.Text))
                       @(Hs.Map Hs.Text Hs.Text)
                       (obj .: "metadata"))))
 
instance HsJSONPB.ToJSON ConfigurationItem where
        toJSON = HsJSONPB.toAesonValue
        toEncoding = HsJSONPB.toAesonEncoding
 
instance HsJSONPB.FromJSON ConfigurationItem where
        parseJSON = HsJSONPB.parseJSONPB
 
instance HsJSONPB.ToSchema ConfigurationItem where
        declareNamedSchema _
          = do let declare_value = HsJSONPB.declareSchemaRef
               configurationItemValue <- declare_value Proxy.Proxy
               let declare_version = HsJSONPB.declareSchemaRef
               configurationItemVersion <- declare_version Proxy.Proxy
               let declare_metadata = HsJSONPB.declareSchemaRef
               configurationItemMetadata <- declare_metadata Proxy.Proxy
               let _ = Hs.pure ConfigurationItem <*>
                         (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @(Hs.Text)
                            (HsJSONPB.asProxy declare_value))
                         <*>
                         (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @(Hs.Text)
                            (HsJSONPB.asProxy declare_version))
                         <*>
                         (HsProtobuf.unsafeCoerceOver
                            @(Hs.Map (HsProtobuf.String Hs.Text) (HsProtobuf.String Hs.Text))
                            @(Hs.Map Hs.Text Hs.Text)
                            (HsJSONPB.asProxy declare_metadata))
               Hs.return
                 (HsJSONPB.NamedSchema{HsJSONPB._namedSchemaName =
                                         Hs.Just "ConfigurationItem",
                                       HsJSONPB._namedSchemaSchema =
                                         Hs.mempty{HsJSONPB._schemaParamSchema =
                                                     Hs.mempty{HsJSONPB._paramSchemaType =
                                                                 Hs.Just HsJSONPB.SwaggerObject},
                                                   HsJSONPB._schemaProperties =
                                                     HsJSONPB.insOrdFromList
                                                       [("value", configurationItemValue),
                                                        ("version", configurationItemVersion),
                                                        ("metadata", configurationItemMetadata)]}})

